### ISSUE TITLE
Error setting up project (both normal way and docker)

### ISSUE THREAD

**Issue by CaoHoangTung** [JChiyah/crwiz#1]
I cannot setup the project both by `python run.py` and `docker-compose up`

Both method gives the following error (in cmd line and in docker container)
`AttributeError: 'SQLAlchemy' object has no attribute 'Binary'`

It seems that the sql file in /logs is missing?

**Comment by JChiyah** [comment]
Thanks for letting me know! I can confirm that I have this when doing a clean install.

It seems like it is an issue with a newer version of SQLAlchemy. I updated the repository so now Binary is LargeBinary, see here: [https://stackoverflow.com/questions/65851741/attributeerror-module-sqlalchemy-has-no-attribute-binary](https://stackoverflow.com/questions/65851741/attributeerror-module-sqlalchemy-has-no-attribute-binary)

Could you update the repository and try again? Note that I also renamed the master branch to be called main. Let me know if all works to close this issue.
